# Generated by Django 4.1.3 on 2022-11-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_ipdaycount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmodel',
            name='end_ip',
        ),
        migrations.RemoveField(
            model_name='ipmodel',
            name='start_ip',
        ),
    ]
